### ISSUE TITLE
AutoAttack

### ISSUE THREAD

**Issue by Yeez-lee** [Harry24k/adversarial-attacks-pytorch#26]
Hi, I feel confused about the multi-attack and target apgdt. (1) For the standard autoattack, do all images are attacked by 4 attacks respectively and calculate the average robust accuracy after all? (2) And for target apgdt, how the target label is found? I see that the number of target label is equal to the number of total class minus one for CIFAR-10. The question is in this line (https://github.com/Harry24k/adversarial-attacks-pytorch/blob/85bf8ba950b288edf443885bd87ace974dac62b5/torchattacks/attacks/apgdt.py#L106). If I want to use it for the ImageNet, should I set n_target_classes = 999?

Looking forwards to your help! Thanks!

**Comment by Harry24k** [comment]
(1) Usually, in recent studies, the robust accuracy with multiple adversarial attacks is calculated as follows:
An example is considered false if it is once misclassified by any of the adversarial attacks.

(2) Basically, APGDT or (APGD-Targeted) uses all possible other classes as the target label. Thus, APGDT requires the number of classes (`n_classes`) to attack. However, it is possible to set `self.n_target_classes` as the value less than `n_classes`. This indicates that APGDT uses only top-k labels to generate adversarial examples where k is  `self.n_target_classes`-2.

**Comment by Yeez-lee** [comment]
Thanks for the response! I'm clearer than before but still have some questions.
 (1) For example, given 100 clean images, untargeted APGD-CE (no restarts) successfully perturbs 80 ones,
targeted APGD-DLR (9 target classes) successfully perturbs 70 ones, targeted FAB (9 target classes), successfully perturbs 65 ones, and Square Attack (5000 queries) successfully perturbs 60 ones. Suppose that we have 45 ones that are successfully perturbed by all 4 attacks together and 90 ones that are successfully perturbed by at least one of 4 attacks , do you mean that  autoattack regards 90 ones as the final perturbed images? and the robust accuracy is 10/100 = 10%.
(2) I know that APGDT uses  top-k ( k=9) labels to generate adversarial examples and I see the codes.
https://github.com/Harry24k/adversarial-attacks-pytorch/blob/85bf8ba950b288edf443885bd87ace974dac62b5/torchattacks/attacks/apgdt.py#L233
 So why do we need the for loop instead of directedly using the case that we find the best target in the top-9 labels? And finally is only the best case saved or are all 9 cases saved for current for loop?
 (3) In the codes,
https://github.com/Harry24k/adversarial-attacks-pytorch/blob/85bf8ba950b288edf443885bd87ace974dac62b5/torchattacks/attacks/apgdt.py#L84
Why do we need to use the norm twice in Line 92 and 145? Normally, we just use the norm once to constrain the generated ones in the last few steps like the second one below.
 https://github.com/Harry24k/adversarial-attacks-pytorch/blob/85bf8ba950b288edf443885bd87ace974dac62b5/torchattacks/attacks/apgdt.py#L92
https://github.com/Harry24k/adversarial-attacks-pytorch/blob/85bf8ba950b288edf443885bd87ace974dac62b5/torchattacks/attacks/apgdt.py#L145
 
 Thanks for your help again!

**Comment by Harry24k** [comment]
Thanks for the response! I'm clearer than before but still have some questions.
(1) In this case, autoattack regards 90 ones as the final perturbed images. Specifically, during the attack process, the images which are not perturbed by one attack passed to the next attack to reduce the computational cost. Thus, the robust accuracy is 10/100 = 10%. In another case that given 100 clean images, each one is firstly attacked by untargeted APGD-CE (no restarts) and if it succeeds for all images, the last attacks will not be used (because it already achieved 0% robust accuracy).

(2) As mentioned above, there is no need to memorize the best case adversarial examples as it uses Linf norm. In the case of L2 norm, we usually consider adversarial examples with the smallest L2 distance as the best (and final) adversarial examples). Thus, only the first case is saved.

(3) The norm in Line 92 is for random initialization, and the norm in Line 145 is for clipping the images to the epsilon ball.
