### ISSUE TITLE
normalize question

### ISSUE THREAD

**Issue by LD-Rocky** [Harry24k/adversarial-attacks-pytorch#69]
hi，i have a question about normalize，your demo White Box Attack (ImageNet).ipynb use the class Normalize you designed,it is same as the normalize in the transforms.Normalize?

If they are different, what are their differences？

**Comment by Harry24k** [comment]
`transforms.Normalize` gives us a normalized image `x_norm`, and then we generally feed it to the model.
However, in this case, `x_norm` does not have a range of [0, 1]. This leads to wrong clipping during the attack process.
Thus, we need to pass the original image `x` with a range of [0, 1] to the attack instead of `x_norm` using Normalize class in the model instead of changing the original image.
